### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by lcx1874000** [CBalance/SSD#1]
Hello, there seems to be a problem with the connection of the paper, can you republish it

**Comment by CBalance** [comment]
Well, the work on ijcai24's officially accepted paper is not complete, so we have not made the paper available yet. Could you please be patient and wait for our updated final version of the paper or a possible preprint after some time?

**Comment by lcx1874000** [comment]
Ok, when do you expect it to be released

**Comment by CBalance** [comment]
> Ok, when do you expect it to be released

We've updated the link to the paper on the homepage.
