### ISSUE TITLE
How much memory is needed on a single GPU to train an SSD model?

### ISSUE THREAD

**Issue by bebop98** [CBalance/SSD#2]
Thanks for your work. I have a GPU with 24G memory, but I set the batch size to 1 and still cannot train SSD. What is the minimum single GPU memory required for training?

**Comment by CBalance** [comment]
> Thanks for your work. I have a GPU with 24G memory, but I set the batch size to 1 and still cannot train SSD. What is the minimum single GPU memory required for training?

With a 48GB GPU, I can set the batch size to 4. A 24GB GPU should be sufficient to run 1 batch. If your device still cannot handle it, you can try reducing the maximum expansion factor in the dynamic scale strategy of the SSD model structure, or remove this step altogether. This should help resolve the memory shortage issue.

**Comment by bebop98** [comment]
> > Thanks for your work. I have a GPU with 24G memory, but I set the batch size to 1 and still cannot train SSD. What is the minimum single GPU memory required for training?
> 
> With a 48GB GPU, I can set the batch size to 4. A 24GB GPU should be sufficient to run 1 batch. If your device still cannot handle it, you can try reducing the maximum expansion factor in the dynamic scale strategy of the SSD model structure, or remove this step altogether. This should help resolve the memory shortage issue.

Thanks for your reply, I will try it
